GymTypes:
- Water
- Electric
- Grass
- Rock
- Normal
- Ground
- Ice
- Fighting
- Fire
- Psychic
Gyms:
  Water:
    Leaders:
    - Ryalane
    Status: true
    Color: BLUE
  Electric:
    Leaders:
    - Ryalane
    Status: true
    Color: GOLD
  Grass:
    Leaders:
    - Ryalane
    Status: true
    Color: GREEN
  Rock:
    Leaders:
    - Ryalane
    Status: true
    Color: DARK_GRAY
  Normal:
    Leaders:
    - Ryalane
    Status: true
    Color: LIGHT_PURPLE
  Ground:
    Leaders:
    - Ryalane
    Status: false
    Color: GRAY
  Ice:
    Leaders:
    - Ryalane
    Status: true
    Color: AQUA
  Fighting:
    Leaders:
    - Ryalane
    Status: false
    Color: BOLD
  Fire:
    Leaders:
    - Ryalane
    Status: true
    Color: RED
  Psychic:
    Leaders:
    - Ryalane
    Status: false
    Color: DARK_PURPLE
