GymTypes:
- Water
- Electric
- Grass
- Rock
- Normal
- Ground
- Ice
- Fighting
- Fire
- Psychic
Gyms:
  Water:
    Leaders:
    - Ryalane
    Status: false
  Electric:
    Leaders:
    - Ryalane
    Status: false
  Grass:
    Leaders:
    - Ryalane
    Status: false
  Rock:
    Leaders:
    - Ryalane
    Status: false
  Normal:
    Leaders:
    - Ryalane
    Status: false
  Ground:
    Leaders:
    - Ryalane
    Status: false
  Ice:
    Leaders:
    - Ryalane
    Status: false
  Fighting:
    Leaders:
    - Ryalane
    Status: false
  Fire:
    Leaders:
    - Ryalane
    Status: false
  Psychic:
    Leaders:
    - Ryalane
    Status: false
