name: Leaders
version: 0.9.4
main: me.Ryalane.Leaders.Leader
author: Ryalane1
description: Leaders
commands:
    Leader:
        description: "Open or close the gym. /leader <open/close> <gym>"
        usage: /leader <open/close> <gym>
        permission: leaders.leader
        permission-message: "Sorry, you aren't a leader."
    Gym:
        description: "Use the Gym commands. Type /Gym info for more commands."
        usage: /gym <gymname>
        permission: leaders.gym
permissions:
    leaders.*:
        description: Gives access to all leader commands
        default: false
        children:
          leaders.toggle:
            description: Open or close the gym
            default: false
          leaders.add:
            description: Gives access to the Add command
            default: false
          leaders.del:
            description: Gives access to the Del command
            default: false
    gym.*:
        description: Gives access to all gym commands
        default: true
        children:
          gym.list:
            description: Lists all leaders of the specified gym